name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Run checks
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run linter
        run: yarn run lint
      - name: Install Cygwin (Windows)
        if: runner.os == 'Windows'
        uses: cygwin/cygwin-install-action@master
      - name: Install nobl9-language-server
        run: |
          set -o pipefail
          curl -fsSL https://raw.githubusercontent.com/nobl9/nobl9-language-server/main/install.bash | bash
        shell: bash
      - name: Run tests
        uses: coactions/setup-xvfb@v1
        with:
          run: yarn run test
